{% set version = '1.1.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-argparse
  version: {{ version|replace("-", "_") }}

source:
  fn: argparse_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/argparse_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/argparse/argparse_{{ version }}.tar.gz
  sha256: 441449f0816411a868fd1b15cf4b2bc45931bbd4b67d6592dbe48875905cf93b

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr (>= 1.15.19), testthat
requirements:
  build:

  host:
    - r-base
    - r-findpython
    - r-getopt >=1.19
    - r-jsonlite
    - r-proto >=1.0.0

  run:
    - r-base
    - r-findpython
    - r-getopt >=1.19
    - r-jsonlite
    - r-proto >=1.0.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('argparse')"           # [not win]
    - "\"%R%\" -e \"library('argparse')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/trevorld/argparse
  license: GPL (>= 2)
  summary: A command line parser to be used with Rscript to write "#!" shebang scripts that gracefully
    accept positional and optional arguments and automatically generate usage.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: argparse
# Type: Package
# Title: Command Line Optional and Positional Argument Parser
# Version: 1.1.1
# Author: Trevor L Davis. Ports examples from the argparse Python module by the Python Software Foundation. Ports examples from the getopt package by Allen Day.
# Maintainer: Trevor L Davis <trevor.l.davis@gmail.com>
# Description: A command line parser to be used with Rscript to write "#!" shebang scripts that gracefully accept positional and optional arguments and automatically generate usage.
# License: GPL (>= 2)
# Copyright: See file (inst/)COPYRIGHTS.
# URL: https://github.com/trevorld/argparse
# BugReports: https://github.com/trevorld/argparse/issues
# LazyLoad: yes
# Imports: proto (>= 1.0.0), findpython, getopt (>= 1.19), jsonlite
# SystemRequirements: python (>= 3.2)
# Suggests: knitr (>= 1.15.19), testthat
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-01-24 18:52:54 UTC; trevorld
# Repository: CRAN
# Date/Publication: 2018-01-24 19:16:15 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
