travis:
  secure:
    BINSTAR_TOKEN: iadEdjQ1mO/Zkxra5fc+OhNrLW9sBblqGwOEB/C9duM0sFsP+jpCapitoPiNiQkTO2EMnY7pQpjYRvczNgW7yLS/vuUTSw0O1lLGFq6zunFfloDA0dSttHqRpniYwmX6wuf6p/3r3beu2YdK7ZEBLB/kpku7/0XmBLkfgM8L1X31rf53bmCEKsRwCUi+nShxS8T0+AyTijNfm9R2utq9SxbM7+AHSdJTvD4mdk8j1KJBxCbyob1PHSSXaTaew+8DdMf4sX5X4BdF2IDW3XL74Eo06xkhuJbd+KnmBoMUT7M7/aSOBg6t0/E8y1TZW09l/KyMs3aPagP3RnzzrvPgDVNzGe6LI8VoDbyCuJL1diSc0Z4kc8XlQVaCGaMgPrXiyRxrfY96Fic6KaZj2RCCXaJfutU1bvLnXA0wWVCK192PjTTONoa0DfkmLE6rzBWBTKTzgFlKn4LdL6R+abRaJOu+gB0fkDq5gmBTQqbny9nGgqK1ZGmOlA5u6zHksUto0+IN2mT89mxdnYt1wr2wpW2VcKbFaHm7ypvTGXjmz4qPlGK6rLN4Nr4W7JxSb9EmLTnbXDSTN1dnH63Hpzt6ZMr/VFT1VeUK1zQMsO3DHe4OG/YuRn53QTWPyWCA/lhZaKukATjX4P7wE91SYDz6OletOYMdKDqoxM/9PD+q++A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
