travis:
  secure:
    BINSTAR_TOKEN: Jn/iJSD6Ou3xZASvGOFLNKdAdb6nTXjkn0guvHq1xWBmIVzRAM6dNU2AhJ6hsVrkdffbqgOhsVdix1gdBgcSMGINzn1+VGxhLidBQIlHVhf9VGvwY1YGRbXd8T3R2W9pSo1MwLCahGznT9bP3DsvnAGASFPMJO4POU4bAPwsRVeed0f76uuMNeE8MPkVrN3SdWrhKsvINYHXfvjSJ8tfHTpmhHux3unIh5fZRCb4KxjtMWvJvMvmb2gLpQBppRHRt+E7CTmnB3pA8EOj+mz5wKhUboYfratJVR6Qqv2/bOPJ5iuWApvQqun/8wsqSbvbrdoxDsS0PBH4Oo7hjMgdv3JPX7V2MR+u55Jm2LRU+tpXrS0CiKXss1TNa8QVTs3NnQLJgL8uA4cFOYmiRDlFiAQeoF52FUoAYFNCgnZq1IyPj4fyLArMe5jOq3LvXTmQD79zo4e27C4id039SWKNWw8kVpaA79CmUpvmuRt1rVI/QGh4Jy6/kpkDTYEAnb1+iyOssR0VbGv6zT1eQCA9wvO6yX0keWLX2EflJ9h+4EsOkuMFNB/5vzYE205hSpIxEpJKhtu3SBp9mvo39L4b7x8yQYNwYRPek/ZIJS/M8SbxZFz7oxmjiWrHSE09mMdB/Z7D2B2X3OQ0N6ewuE7gTj9eijrbsFDS1QOTk6govMc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
