travis:
  secure:
    BINSTAR_TOKEN: U45REoir9WfNpwaKYjTNBUFmGAjVtO4atnEZwq/hnl5X7Zs8JDQ6V60Cib+lC7w/cskvBvoyDER8nrO29gHJMhrs+XPF42MjWDhQTfTHFqPt3uDhGN/MyYoMdsCWQdpYuTGViDY4mBfiEZtWGObHR29KDq7n8sQj4JChkhOez0snc/7s8euCxUpUDkU4TBqu3qOtNsytUgEPPL0+AIhva65QRCEiWrcUWt7KU/7rsR7RPDDeW3gx5ETy47ddvWR1g+woftps7v5CvqPQhqfhv4t3BVpNTMCfRObtkLqSC3GCtZtmMKtf5GeprDyjaMRpJYCMbBcg+6zOoU3bzOlne5+DZa5vzgZ4QG9MYsXzwZzSSc14jMBSLmqoZ8xAGVqolcSKE9h0/o/05ifSnIFjRphlkUoO1Fr8BbemY0hp77zC1F4lzSrwCgQbMLZPgepMvdNEbJlYzAGyBV5QLUN8i69KvHUe43FdaJ+0bMos+V4D5yiWA5WX6pfzcJ+yGapJGHkOi6JAZnRw+hDB5HSv63kpQy2UPazxR6zNfqExbWtLiv2fwjl5NtGvl+Il/vzjVUGa2mqAEFBrsMmpn2Jlm9GVdyqDfhv6uiR5s1RohQg69qazYVbyWOR1xaAWuZBmvdftb7ukMenlSySUAffwIWf0APl4Ci5buA2YcP0KrI8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
